/*!
 * ********************************************************************************************************************************
 * @file        ProjectSourceGenerator.cpp
 * @brief       Project source aggregation and output generation.
 * @details     Generates Project-Source.txt including metadata, project tree, and source file contents.
 * @authors     Jeffrey Scott Flesher with the help of AI: Copilot
 * @date        2026-04-02
 *********************************************************************************************************************************/
#include "ProjectSourceGenerator.h"

#include "ProjectTreeBuilder.h"

#include <QDir>
#include <QDirIterator>
#include <QFile>
#include <QFileInfo>
#include <QTextStream>

/*!
 * ****************************************************************************************************************************
 * @brief   Determine whether a path should be excluded.
 * @details Exclusion applies ONLY to top-level directories (root children).
 * @param   relativePath Path relative to project root.
 * @param   excludeDirs Directory exclusion patterns.
 * @return  True if the path should be excluded.
 *****************************************************************************************************************************/
static bool shouldExcludePath(const QString &relativePath, const QStringList &excludeDirs)
{
    const int slashIndex = relativePath.indexOf(QLatin1Char('/'));
    const QString topLevel = slashIndex == -1 ? relativePath : relativePath.left(slashIndex);

    for (int i = 0; i < excludeDirs.size(); ++i)
    {
        const QString &pattern = excludeDirs.at(i);
        if (pattern.endsWith('*') && topLevel.startsWith(pattern.left(pattern.size() - 1))) return true;
        if (!pattern.endsWith('*') && topLevel == pattern) return true;
    }

    return false;
}

/*!
 * ****************************************************************************************************************************
 * @brief   Write the formatted project tree to Project-Source.txt.
 * @details Replaces the former PackSource.cmake psd_write_project_tree() behavior.
 * @param   out QTextStream bound to Project-Source.txt.
 * @param   projectRoot Absolute project root directory.
 * @param   excludeDirs Directory exclusion patterns.
 *****************************************************************************************************************************/
void ProjectSourceGenerator::writeProjectTree(QTextStream &out, const QString &projectRoot, const QStringList &excludeDirs)
{
    out << ProjectTreeBuilder::buildProjectTreeText(projectRoot, excludeDirs);
}

/*!
 * ****************************************************************************************************************************
 * @brief   Generate Project-Source.txt for a project.
 * @details Fully replaces PackSource.cmake file aggregation behavior.
 * @param   projectRoot Absolute project root directory.
 * @param   includeExts File extensions to include.
 * @param   excludeDirs Directory exclusion patterns.
 * @param   outFilePath Absolute output file path.
 * @return  True on success; false on failure.
 *****************************************************************************************************************************/
bool ProjectSourceGenerator::generateProjectSource(const QString &projectRoot, const QStringList &includeExts, const QStringList &excludeDirs, const QString &outFilePath)
{
    if (projectRoot.isEmpty() || !QDir(projectRoot).exists()) return false;

    QFile outFile(outFilePath);
    if (!outFile.open(QIODevice::WriteOnly | QIODevice::Truncate | QIODevice::Text)) return false;

    QTextStream out(&outFile);

    const QString divider = QStringLiteral("===================================================================================================================================\n");

    out << QStringLiteral("Project-Source.txt\n");
    out << QStringLiteral("Generated by ProjectSourceGenerator\n");
    out << QStringLiteral("Root: ") << projectRoot << QLatin1Char('\n');
    out << QStringLiteral("Included extensions: ") << includeExts.join(QStringLiteral("; ")) << QLatin1Char('\n');
    out << QStringLiteral("Excluded dirs: ") << excludeDirs.join(QStringLiteral("; ")) << QLatin1Char('\n');
    out << QLatin1Char('\n');

    writeProjectTree(out, projectRoot, excludeDirs);

    QDirIterator it(projectRoot, QDir::Files | QDir::NoSymLinks, QDirIterator::Subdirectories);

    while (it.hasNext())
    {
        const QString absPath = it.next();
        const QString relPath = QDir(projectRoot).relativeFilePath(absPath);

        if (relPath == QStringLiteral("Project-Source.txt")) continue;
        if (shouldExcludePath(relPath, excludeDirs)) continue;

        const QFileInfo info(absPath);
        const QString ext = info.suffix().toLower();
        if (!includeExts.contains(ext)) continue;

        QFile file(absPath);
        if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) continue;

        out << divider;
        out << QStringLiteral("=============================== FILE: ") << relPath << QStringLiteral(" ===============================\n");
        out << divider;
        out << file.readAll() << QLatin1Char('\n');
    }

    outFile.close();
    return true;
}

/*!
 * ********************************************************************************************************************************
 * @brief End of ProjectSourceGenerator.cpp
 *********************************************************************************************************************************/
